kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node:20
    commands:
      - npm install
  - name: build
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t myapp:${DRONE_COMMIT_SHA:0:8} .

  - name: deploy
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - |
        if docker ps -a --format '{{.Names}}' | grep -q "^myapp$"; then
          echo "Found existing myapp container. Stopping and removing..."
          docker stop myapp
          docker rm myapp
        else
          echo "No existing myapp container found. Proceeding with first deployment..."
        fi

        echo "Starting new container..."
        docker run -d --name myapp -p 3003:3003 myapp:${DRONE_COMMIT_SHA:0:8}

        if docker ps --format '{{.Names}}' | grep -q "^myapp$"; then
          echo "Container deployed successfully!"
        else
          echo "Failed to deploy container!"
          exit 1
        fi

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
